# Generated by Django 2.0.13 on 2022-11-04 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerName', models.CharField(max_length=50, verbose_name='名称')),
                ('bannerImg', models.ImageField(default='', upload_to='banner/%Y/%m/%d', verbose_name='广告')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10, verbose_name='商品编号')),
                ('productnum', models.IntegerField(verbose_name='商品数量')),
                ('productprice', models.CharField(max_length=10, verbose_name='利润')),
                ('isChose', models.BooleanField(default=True)),
                ('productimg', models.CharField(max_length=150)),
                ('productname', models.CharField(max_length=100)),
                ('orderid', models.CharField(default='0', max_length=20, verbose_name='订单编号')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '销售',
                'verbose_name_plural': '销售管理',
                'db_table': 'shop_cart',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=10)),
                ('typename', models.CharField(max_length=20)),
                ('typesort', models.IntegerField()),
                ('childtypenames', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10, verbose_name='商品编号')),
                ('productimg', models.CharField(max_length=150, verbose_name='图片')),
                ('productname', models.CharField(max_length=50, verbose_name='名称')),
                ('price', models.CharField(max_length=10, verbose_name='进价')),
                ('marketprice', models.CharField(max_length=10, verbose_name='售价')),
                ('storenums', models.IntegerField(verbose_name='库存')),
                ('productnum', models.IntegerField(verbose_name='销量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜单管理',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20, verbose_name='订单编号')),
                ('totalprice', models.IntegerField(verbose_name='总价')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'db_table': 'shop_order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('userPasswd', models.CharField(max_length=20, verbose_name='密码')),
                ('userName', models.CharField(max_length=20, verbose_name='名称')),
                ('userPhone', models.CharField(max_length=20, verbose_name='手机')),
                ('userAdderss', models.CharField(max_length=100, verbose_name='地址')),
                ('userImg', models.ImageField(default='', upload_to='media', verbose_name='用户头像')),
                ('userRank', models.IntegerField(verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员管理',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User', verbose_name='用户'),
        ),
    ]
