# Generated by Django 2.0.13 on 2022-11-04 15:21

from django.db import migrations, models
import media.storage


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bannerImg',
            field=models.ImageField(default='', storage=media.storage.ImageStorage(), upload_to='banner/%Y%m', verbose_name='广告'),
        ),
    ]
